# num= int(input('enter a type:'))
# print(type(num))
# value= float(input('enter a value:'))
# print(type(value))
# past= bool(input('enter a variable:'))
# print(type(past))
# user=complex(input('enter a type:'))
# print(type(user))
# name=str(input('enter a name:'))
# print(type(name))

num=eval(input('enter a type:'))
print(type(num))